POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImZvb2JhcjMiLCJpZCI6IjYzNzNiMjAwNjRjMDg1MDBkYzI4NjJiNSIsImlhdCI6MTY2ODUyNzc1MiwiZXhwIjoxNjY4NTMxMzUyfQ.Zs29ggcKeuOAnGaZaWL4Iv5MzbMjARtDPPhHshr_ORY

{
  "title": "Test blog",
  "author": "Liina",
  "url": "http://something",
  "likes": 10
}