PUT http://localhost:3003/api/blogs/63984cf9195e047cd17efc3f
Content-Type: application/json

{
  "title": "Updated blog",
  "author": "Liina",
  "url": "http://something",
  "likes": 0,
  "comments": ["yksi", "kaksi"]
}